Repository KaungKhantSiThu/abac-drift-front-end, pull requests merged in 2023-03, with the labels that each got.

#6 added login auth
  .env
  .nuxt/dev/index.mjs
  .nuxt/dev/index.mjs.map
  .nuxt/imports.d.ts
  .nuxt/nuxt.d.ts
  .nuxt/types/imports.d.ts
  .nuxt/types/middleware.d.ts
  .nuxt/types/nitro.d.ts
  .nuxt/types/plugins.d.ts
  .nuxt/types/schema.d.ts
  .nuxt/types/supabase.d.ts
  components/Nav/Header.vue
  composables/appointmentStore.ts
  middleware/auth.ts
  nuxt.config.ts
  package-lock.json
  package.json
  pages/appointments/index.vue
  pages/index.vue
  pages/login/index.vue
  pages/motorcycles/index.vue
  server/api/appointments/index.get.ts
  server/api/motorcycles/index.get.ts
  server/models/Appointment.model.ts
  server/models/Motorcycle.model.ts
  types/index.ts
Labels: implementation

#8 Renatta branch
  .nuxt/components.d.ts
  .nuxt/dev/index.mjs
  .nuxt/dev/index.mjs.map
  .nuxt/nuxt.json
  .nuxt/types/layouts.d.ts
  assets/bootstrap.bundle.min.js
  assets/bootstrap.min.css
  components/MotorcycleDetails.vue
  components/MotorcycleModal.vue
  components/Nav/Header.vue
  components/ProductCard.vue
  composables/motorcycleStore.ts
  package-lock.json
  package.json
  pages/MotorDetails/index.vue
  pages/motorcycles/index.vue
  public/assets/motorcycle/au.png
  public/assets/motorcycle/bike_one.png
  public/assets/motorcycle/bike_three.jpg
  public/assets/motorcycle/bike_two.jpg
  public/assets/motorcycle/pepa.jpg
  public/assets/motorcycle/pepe.jpg
Labels: vue component, vue page, implementation

#10 UI improvement
  .nuxt/dev/index.mjs
  .nuxt/dev/index.mjs.map
  .nuxt/imports.d.ts
  .nuxt/nuxt.d.ts
  .nuxt/nuxt.json
  .nuxt/types/layouts.d.ts
  .nuxt/types/middleware.d.ts
  .nuxt/types/plugins.d.ts
  .nuxt/types/schema.d.ts
  .nuxt/types/supabase.d.ts
  components/AppointmentCard.vue
  components/MotorcycleModal.vue
  components/Nav/Header.vue
  components/ProductCard.vue
  package-lock.json
  pages/appointments/[id].vue
  pages/motorcycles/[id].vue
  pages/motorcycles/index.vue
  public/assets/images/au.png
  public/assets/images/bike_three.jpg
  public/assets/images/bike_two.jpg
  public/assets/images/pepa.jpg
  public/assets/images/pepe.jpg
Labels: enhancement

#13 UI nearly final version
  .nuxt/dev/index.mjs
  .nuxt/dev/index.mjs.map
  .nuxt/imports.d.ts
  components/RegistrationModal.vue
  pages/index.vue
  pages/login/index.vue
  public/assets/images/HomePageMoto.jpg
  public/assets/images/SecondHomeMoto.jpg
Labels: enhancement
